    steps:
      - uses: actions/checkout@v4

      # AGGIUNGI QUESTO BLOCCO QUI SOTTO:
      - name: Clone Geode CMake Framework
        run: git clone https://github.com/geode-sdk/cmake.git geode-cmake

      - uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          
