name: Build Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android 64-bit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Geode CMake Framework
        run: |
          curl -L https://github.com/geode-sdk/cmake/archive/refs/heads/main.zip -o cmake.zip
          unzip cmake.zip
          mv cmake-main geode-cmake

      - name: Compile Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          
